language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_12db36da23be_key -iv $encrypted_12db36da23be_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- pip install codecov
script: python setup.py test
after_success:
- codecov
