language: python
python: 2.7
env:
  - TOX_ENV=py27
before_install:
- openssl aes-256-cbc -K $encrypted_12db36da23be_key -iv $encrypted_12db36da23be_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- pip install tox
script: tox -e $TOX_ENV
